# base image node alpine
FROM node:20-alpine
# set working directory
WORKDIR /app
# copy package.json and package-lock.json
COPY package*.json ./
# install dependencies
RUN npm install
# copy all files
COPY . .
# run test command
CMD ["npm", "test"]